"""Multi-view image generation using OpenAI image generation API.

Given a single corner-angle photo, generates the 3 canonical views
(front, side, top) needed for 3D reconstruction.

Camera coordinate convention (matches gpu-cluster canonical_mv):
    - World space: Y-up, right-handed
    - Subject centered at origin (0, 0, 0)
    - Camera distance: 2.5 units from origin
    - front:  camera at (0, 0, +2.5) looking along -Z
    - side:   camera at (+2.5, 0, 0) looking along -X
    - top:    camera at (0, +2.5, 0) looking down along -Y
"""

from __future__ import annotations

import asyncio
import base64
import logging
import mimetypes
import shutil
from pathlib import Path
from typing import Optional

from .config import config

logger = logging.getLogger("brickedup.views")

CANONICAL_VIEWS = ["front", "side", "top"]

_SHARED_PREAMBLE = (
    "You are generating one view of a multi-view orthographic reference sheet "
    "for 3D reconstruction. The following rules are CRITICAL:\n\n"
    "1. SAME OBJECT: The subject must be the EXACT same object as the input image. "
    "Preserve every detail: shape, proportions, colors, textures, markings.\n"
    "2. CONSISTENT POSE: The object does NOT move or rotate. Only the camera moves.\n"
    "3. CENTERED: The subject must be perfectly centered in the frame.\n"
    "4. FILL FRAME: The subject should occupy about 60-70 percent of the image.\n"
    "5. PURE WHITE BACKGROUND: Uniform white (#FFFFFF). No shadows, no floor.\n"
    "6. FLAT LIGHTING: Perfectly even diffuse lighting. No cast shadows or highlights.\n"
    "7. NO PERSPECTIVE DISTORTION: Use near-orthographic projection.\n\n"
)

VIEW_PROMPTS = {
    "front": (
        _SHARED_PREAMBLE
        + "CAMERA: Directly in front at (0, 0, +2.5), looking along -Z.\n\n"
        "Perfectly straight-on FRONT view at eye level. Show only the front face "
        "of the object, centered, with equal space on all sides. No sides, top, "
        "or back visible. Perpendicular to the front face."
    ),
    "side": (
        _SHARED_PREAMBLE
        + "CAMERA: Directly to the RIGHT at (+2.5, 0, 0), looking along -X.\n\n"
        "Perfectly straight-on RIGHT SIDE view at eye level. Show the right side "
        "profile. The FRONT of the object faces the RIGHT edge of the image. "
        "No front, back, left, or top visible. Perpendicular to the right face."
    ),
    "top": (
        _SHARED_PREAMBLE
        + "CAMERA: Directly ABOVE at (0, +2.5, 0), looking straight down along -Y.\n\n"
        "Perfectly straight-down BIRD'S-EYE view. Show only the top surface. "
        "The front of the object faces toward the bottom of the image. "
        "No sides visible. Perpendicular to the top surface."
    ),
}


async def generate_views(
    input_image_path: str,
    output_dir: str,
    views_to_generate: Optional[list[str]] = None,
    on_progress: Optional[callable] = None,
) -> dict[str, str]:
    """Generate canonical views from a corner-angle input image using OpenAI.

    Each view is generated by sending the subject input image alongside
    a precise camera-position prompt.

    Args:
        input_image_path: Path to the input image.
        output_dir: Directory to save generated views.
        views_to_generate: Which views to generate (default: all 3).
        on_progress: Callback(view_name, status) for progress updates.

    Returns:
        Dict mapping view name to file path.
    """
    from openai import AsyncOpenAI

    views = views_to_generate or CANONICAL_VIEWS
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    input_path = Path(input_image_path)
    with open(input_path, "rb") as f:
        image_bytes = f.read()
    image_b64 = base64.b64encode(image_bytes).decode("utf-8")

    mime, _ = mimetypes.guess_type(str(input_path))
    media_type = mime or "image/png"

    client = AsyncOpenAI(api_key=config.OPENAI_API_KEY)

    input_copy = out_dir / f"input{input_path.suffix}"
    shutil.copy2(input_path, input_copy)

    results: dict[str, str] = {"input": str(input_copy)}

    semaphore = asyncio.Semaphore(2)

    async def gen_one(view_name: str) -> tuple[str, str]:
        async with semaphore:
            if on_progress:
                on_progress(view_name, "generating")

            output_path = out_dir / f"{view_name}.png"
            prompt = VIEW_PROMPTS[view_name]

            try:
                response = await client.images.edit(
                    model=config.IMAGE_GEN_MODEL,
                    image=open(input_path, "rb"),
                    prompt=prompt,
                    n=1,
                    size="1024x1024",
                )

                image_url = response.data[0].url
                if response.data[0].b64_json:
                    img_data = base64.b64decode(response.data[0].b64_json)
                    with open(output_path, "wb") as f:
                        f.write(img_data)
                elif image_url:
                    import httpx

                    async with httpx.AsyncClient() as http:
                        img_resp = await http.get(image_url)
                        img_resp.raise_for_status()
                        with open(output_path, "wb") as f:
                            f.write(img_resp.content)

                if on_progress:
                    on_progress(view_name, "complete")

                return view_name, str(output_path)

            except Exception as e:
                logger.error("Failed to generate %s view: %s", view_name, e)
                shutil.copy2(input_path, output_path)
                if on_progress:
                    on_progress(view_name, "fallback")
                return view_name, str(output_path)

    tasks = [gen_one(v) for v in views]
    completed = await asyncio.gather(*tasks)

    for view_name, path in completed:
        results[view_name] = path

    return results


async def generate_views_fallback(
    input_image_path: str,
    output_dir: str,
    views_to_generate: Optional[list[str]] = None,
    on_progress: Optional[callable] = None,
) -> dict[str, str]:
    """Fallback: copy input image as all views (testing without OpenAI key)."""
    views = views_to_generate or CANONICAL_VIEWS
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    input_path = Path(input_image_path)
    results: dict[str, str] = {}

    for view_name in views:
        output_path = out_dir / f"{view_name}.png"
        shutil.copy2(input_path, output_path)
        results[view_name] = str(output_path)
        if on_progress:
            on_progress(view_name, "fallback")

    return results

